# Generated by Django 4.1.1 on 2022-10-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['number'], 'verbose_name_plural': 'Student_List'},
        ),
    ]
