# Generated by Django 4.1.1 on 2022-10-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_model', '0003_student_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name_plural': 'Student_List'},
        ),
    ]
