# Generated by Django 4.1.1 on 2022-10-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
